version: '3.1'
services:
    springapp:
      image: whitewolfimages/spring-app-docker:imageversion
      restart: always
      container_name: springcont
      ports:
      - 8080:8080
      working_dir: /opt/app
      networks:
      - springappnetwork

    mongodb:
      image: mongo
      container_name: mongodb
      volumes:
      - mongomount:/data/db
      restart: always
      networks:
      - springappnetwork

volumes:
  mongomount:
    driver: local
networks:
  springappnetwork:
    driver: bridge

